/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/bio': RouteRecordInfo<'/bio', '/bio', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/interests': RouteRecordInfo<'/interests', '/interests', Record<never, never>, Record<never, never>>,
    '/otp': RouteRecordInfo<'/otp', '/otp', Record<never, never>, Record<never, never>>,
    '/questions': RouteRecordInfo<'/questions', '/questions', Record<never, never>, Record<never, never>>,
    '/questions/gender': RouteRecordInfo<'/questions/gender', '/questions/gender', Record<never, never>, Record<never, never>>,
    '/questions/height': RouteRecordInfo<'/questions/height', '/questions/height', Record<never, never>, Record<never, never>>,
    '/statistics': RouteRecordInfo<'/statistics', '/statistics', Record<never, never>, Record<never, never>>,
    '/verification': RouteRecordInfo<'/verification', '/verification', Record<never, never>, Record<never, never>>,
  }
}
